# Generated by Django 4.1.7 on 2023-05-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_pla_ces_alter_donor_registration_blood_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pla_ces',
        ),
    ]
